name: Build and Test Compiler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            nasm \
            fasm \
            gcc-aarch64-linux-gnu \
            qemu-user \
            gcc-mingw-w64-x86-64 \
            wine64

      - name: Check compilers
        run: |
          aarch64-linux-gnu-gcc --version
          x86_64-w64-mingw32-gcc --version

      - name: Run bootstrap test
        run: chmod +x ./tests/test_bootstrap.sh && ./tests/test_bootstrap.sh
